apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secrets
  namespace: nextcloud
type: Opaque
data:
  username: dXNlcm5hbWU= # base64 encoded username
  password: cGFzc3dvcmQ= # base64 encoded password
  token: bmV4dGNsb3VkLXRva2Vu # base64 encoded nextcloud-token
