version: "3.8"

services:
  
  # Nextcloud main service
  nextcloud:

    image: nextcloud:latest
    container_name: nextcloud
    restart: always
    ports:
      - "8080:80"
    volumes:
      - nextcloud_data:/var/www/html
    environment:
      - NEXTCLOUD_ADMIN_USER=admin # sets the admin username
      - NEXTCLOUD_ADMIN_PASSWORD=password # sets the admin password
      - MYSQL_HOST=db # sets the database host
      - MYSQL_DATABASE=nextcloud # sets the database name
      - MYSQL_USER=admin # sets the database user
      - MYSQL_PASSWORD=password # sets the database password
    networks:
      - nextcloud_network
    depends_on:
      - db
      - redis
  
  # Database service
  db:

    image: mariadb:latest
    container_name: nextcloud_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password # sets the root password
      - MYSQL_DATABASE=nextcloud # sets the database name
      - MYSQL_USER=admin # sets the database user
      - MYSQL_PASSWORD=password # sets the database password
    volumes:
      - nextcloud_db:/var/lib/mysql
    networks:
      - nextcloud_network

  # Redis service for caching
  redis:

    image: redis:latest
    container_name: nextcloud_redis
    restart: always
    networks:
      - nextcloud_network
    volumes:
      - nextcloud_redis:/data

  # locust service for load testing
  locust:

    image: locustio/locust:latest
    container_name: nextcloud_locust
    command: -f /locust-tasks/locustfile.py --host=http://nextcloud:80 # command to run at startup
    restart: always
    ports:
      - "8089:8089"
    volumes:
      - ./locust-tasks:/locust-tasks # for storing tasks
      - ./test_data:/test_data # for storing test data files
    networks:
      - nextcloud_network
    depends_on:
      - nextcloud

# Networks and volumes
networks:
  nextcloud_network:
   external: true
   # (run `docker network create nextcloud_network` to create the network)
     
volumes:
  nextcloud_data:
  nextcloud_db:
  nextcloud_redis:
  