apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: configmap
data:
  config: |
    address-pools:
    - name: ip-address-pool
      protocol: layer2
      addresses:
      - 192.168.121.200-192.168.121.250
